about: Catalog of virtual products for loading Landsat USGS Collection 2 products
products:

    # Landsat 8 USGS Collection 2 Tier 1 Surface Reflectance, rescaled using scaling factors and
    # masked to remove nodata
    ls8_sr:
        recipe:
            &ls8_sr
            transform: expressions
            input:
                product: ls8_sr
                measurements: [blue, green, red, nir, swir_1, swir_2, pixel_quality]
                collection_category: 'T1'
                group_by: solar_day
            output:
                 blue:
                     formula: 2.75e-5 * blue - 0.2
                     dtype: float32
                 green:
                     formula: 2.75e-5 * green - 0.2
                     dtype: float32
                 red: 
                     formula: 2.75e-5 * red - 0.2
                     dtype: float32
                 nir: 
                     formula: 2.75e-5 * nir - 0.2
                     dtype: float32
                 swir_1: 
                     formula: 2.75e-5 * swir_1 - 0.2
                     dtype: float32
                 swir_2: 
                     formula: 2.75e-5 * swir_2 - 0.2
                     dtype: float32
                 pixel_quality: pixel_quality

    # Landsat 7 USGS Collection 2 Tier 1 Surface Reflectance, rescaled using scaling factors and
    # masked to remove nodata    
    ls7_sr:
        recipe:
            &ls7_sr
            transform: expressions
            input:
                product: ls7_sr
                measurements: [blue, green, red, nir, swir_1, swir_2, pixel_quality]
                collection_category: 'T1'
                group_by: solar_day
            output:
                 blue:
                     formula: 2.75e-5 * blue - 0.2
                     dtype: float32
                 green:
                     formula: 2.75e-5 * green - 0.2
                     dtype: float32
                 red: 
                     formula: 2.75e-5 * red - 0.2
                     dtype: float32
                 nir: 
                     formula: 2.75e-5 * nir - 0.2
                     dtype: float32
                 swir_1: 
                     formula: 2.75e-5 * swir_1 - 0.2
                     dtype: float32
                 swir_2: 
                     formula: 2.75e-5 * swir_2 - 0.2
                     dtype: float32
                 pixel_quality: pixel_quality

    # Landsat 5 USGS Collection 2 Tier 1 Surface Reflectance, rescaled using scaling factors and
    # masked to remove nodata
    ls5_sr:
        recipe:
            &ls5_sr
            transform: expressions
            input:
                product: ls5_sr
                measurements: [blue, green, red, nir, swir_1, swir_2, pixel_quality]
                collection_category: 'T1'
                group_by: solar_day
            output:
                 blue:
                     formula: 2.75e-5 * blue - 0.2
                     dtype: float32
                 green:
                     formula: 2.75e-5 * green - 0.2
                     dtype: float32
                 red: 
                     formula: 2.75e-5 * red - 0.2
                     dtype: float32
                 nir: 
                     formula: 2.75e-5 * nir - 0.2
                     dtype: float32
                 swir_1: 
                     formula: 2.75e-5 * swir_1 - 0.2
                     dtype: float32
                 swir_2: 
                     formula: 2.75e-5 * swir_2 - 0.2
                     dtype: float32
                 pixel_quality: pixel_quality

#     # Landsat 8 USGS Collection 2 Tier 1 Surface Reflectance, harmonised 
#     # for compatibility with Landsat 7 ETM+ using empirical corrections 
#     # from Flood 2014 (https://www.mdpi.com/2072-4292/6/9/7952/htm)
#     ls8_sr_harmonised:
#         recipe:
#             &ls8_sr_harmonised
#             transform: expressions
#             input: *ls8_sr
#             output:
#                  blue:
#                      formula: 0.00041 + 0.97470 * blue
#                      dtype: float32
#                  green:
#                      formula: 0.00289 + 0.99779 * green
#                      dtype: float32
#                  red: 
#                      formula: 0.00274 + 1.00446 * red
#                      dtype: float32
#                  nir: 
#                      formula: 0.00004 + 0.98906 * nir
#                      dtype: float32
#                  swir_1: 
#                      formula: 0.00256 + 0.99467 * swir_1
#                      dtype: float32
#                  swir_2: 
#                      formula: -0.00327 + 1.02551 * swir_2
#                      dtype: float32
#                  pixel_quality: pixel_quality
                 
    # Landsat 8 USGS Collection 2 Tier 1 Surface Temperature, 
    # rescaled using scaling factors 
    ls8_st:
        recipe:
            &ls8_st
            transform: expressions
            input:
                product: ls8_st
                measurements: [ST_B10]
                collection_category: 'T1'
                group_by: solar_day
            output:
                 temp:
                     formula: (0.00341802 * ST_B10 + 149.0) - 273.15
                     dtype: float32

    # Landsat 7 USGS Collection 2 Tier 1 Surface Temperature, 
    # rescaled using scaling factors 
    ls7_st:
        recipe:
            &ls7_st
            transform: expressions
            input:
                product: ls7_st
                measurements: [ST_B6]
                collection_category: 'T1'
                group_by: solar_day
            output:
                 temp:
                     formula: (0.00341802 * ST_B6 + 149.0) - 273.15
                     dtype: float32

    # Landsat 5 USGS Collection 2 Tier 1 Surface Temperature, 
    # rescaled using scaling factors 
    ls5_st:
        recipe:
            &ls5_st
            transform: expressions
            input:
                product: ls5_st
                measurements: [ST_B6]
                collection_category: 'T1'
                group_by: solar_day
            output:
                 temp:
                     formula: (0.00341802 * ST_B6 + 149.0) - 273.15
                     dtype: float32    

    # Combined Landsat 5, 7 and 8 USGS Collection 2 Tier 1 Surface Reflectance, 
    # rescaled using scaling factors and masked to remove nodata
    ls_sr:
         recipe:
             &ls_sr
             transform: expressions
             input:
                 collate:
                     - *ls5_sr
                     - *ls7_sr
                     - *ls8_sr
             output: 
                 blue: blue
                 green: green
                 red: red
                 nir: nir
                 swir_1: swir_1
                 swir_2: swir_2
                 pixel_quality: pixel_quality 
    
    # Combined Landsat 5, 7 and 8 USGS Collection 2 Tier 1 Surface Temperature,
    # rescaled using scaling factors and masked to remove nodata
    ls_st:
         recipe:
             &ls_st
             transform: expressions
             input:
                 collate:
                     - *ls5_st
                     - *ls7_st
                     - *ls8_st
             output: 
                 temp: temp

#     # Combined Landsat 5, 7 and 8 USGS Collection 2 Tier 1 data, rescaled 
#     # using scaling factors and masked to remove nodata. Landsat 8 data 
#     # harmonised for compatibility with Landsat 7 ETM+ using empirical 
#     # corrections from Flood 2014 (https://www.mdpi.com/2072-4292/6/9/7952/htm)
#     ls_sr_harmonised:
#          recipe:
#              &ls_sr_harmonised
#              transform: expressions
#              input:
#                  collate:
#                      - *ls5_sr
#                      - *ls7_sr
#                      - *ls8_sr_harmonised
#              output: 
#                  blue: blue
#                  green: green
#                  red: red
#                  nir: nir
#                  swir_1: swir_1
#                  swir_2: swir_2
#                  pixel_quality: pixel_quality 
                   
    # Combined Landsat 5, 7 and 8 USGS Collection 2 Tier 1 Surface Temperature 
    # and Surface Reflectance, rescaled using scaling factors and masked to remove nodata
    ls_sr_st:
         recipe:
             &ls_sr_st
             transform: expressions
             input:
                 juxtapose:
                     - *ls_sr
                     - *ls_st
             output: 
                 blue: blue
                 green: green
                 red: red
                 nir: nir
                 swir_1: swir_1
                 swir_2: swir_2
                 temp: temp
                 pixel_quality: pixel_quality 
                 
    # Combined Landsat 5, 7 and 8 USGS Collection 2 data, converted to MNDWI
    ls_mndwi:
         recipe:
             transform: expressions
             input: *ls_sr_st
             output:
                 pixel_quality: pixel_quality
                 temp: temp
                 mndwi:
                    formula: (green - swir_1) / (green + swir_1)       

#     # Combined Landsat 5, 7 and 8 USGS Collection 2 data, converted to  MNDWI. 
#     # Landsat 8 data harmonised for compatibility with Landsat 7 ETM+ using 
#     # empirical corrections from Flood 2014 
#     # (https://www.mdpi.com/2072-4292/6/9/7952/htm)
#     ls_mndwi_harmonised:
#          recipe:
#              transform: expressions
#              input: *ls_sr_harmonised
#              output:
#                  pixel_quality: pixel_quality
#                  mndwi:
#                     formula: (green - swir_1) / (green + swir_1)
